### ISSUE TITLE
Checksums didn't match expected when downloading virtualbox-iso

### ISSUE THREAD

**Issue by Bradcomp** [udacity/devops-intro-project#1]
I received the following output: 
virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/trusty/ubuntu-14.04.2-server-amd64.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 8acd2f56bfcba2f7ac74a7e4a5e565ce68c024c38525c0285573e41c86ae90c0
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

**Comment by Bradcomp** [comment]
I switched to version 14.04.3 and was able to complete the download using the following checksum
a3b345908a826e262f4ea1afeb357fd09ec0558cf34e6c9112cead4bb55ccdfb *ubuntu-14.04.3-server-amd64.iso

**Comment by MikeiLL** [comment]
Correct line in terminal should be:
`vagrant box add ubuntu-14.04.3-server-amd64-appserver_virtualbox.box --name devops-appserver`

**Comment by sharmadp** [comment]
vagrant up is not working throwing following error 
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`
vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

stdin: is not a tty
/sbin/mount.vboxsf: mounting failed with the error: No such device

**Comment by ffsantos92** [comment]
I have the same issue with v14.04.3. Pull request #10 fix it.

**Comment by mkreisel** [comment]
Can confirm PR #10 resolves the issue for me. Thanks @ffsantos92 !

**Comment by simplydallas** [comment]
It is now v14.04.4 and should be up to date.  Closing this issue as it should not be a problem now until the version rolls again.  If this happens again, remember to update both the hash and the version number in the file because it will check that md5 hash after downloading and error if it is not also correct.

**Comment by iagomr** [comment]
FYI issue is back and it works if you change to "PACKER_BOX_NAME": "ubuntu-14.04.5-server-amd64",

**Comment by pushkarbhatt** [comment]
newbie here, still facing the issue - checksums didn't match expected: 07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a (i see 14.04.4 out there)

**Comment by HieJulia** [comment]
@pushkarbhatt  I got the same problem. Any help?
