### ISSUE TITLE
Fatal error while cloning 

### ISSUE THREAD

**Issue by mithi14** [udacity/devops-intro-project#23]
I am getting "fatal error" when I am trying to clone github. Here are the steps I followed:
1) Install VirtualBox, Vagrant, Git and Packer
2) Create account on Github (mithi14)
3) Type "git clone http://github.com/mithi14/devops-intro-project devops" on git bash

Error:
fatal://http://github.com/mithi14/devops-intro-project/info/refs not valid: is this a git repository?

Please help to proceed

Regards,
Mithila

**Comment by kmmceachern** [comment]
This is super late, but if you've already figured it out for yourself, hopefully this at least helps someone in the future:
First, it looks like your devops-intro-project repo is empty. You'll want to click "Fork" up at the top right of this page to get an exact copy of this repo.
Second, your url is slightly off, which is why the clone failed. 
Once you delete your existing `devops-intro-project` repo and Fork this repo to your account, the command `git clone https://github.com/mithi14/devops-intro-project.git` should work for you.

**Comment by 13rac1** [comment]
@kmmceachern is correct.
